include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    one_member_abstracts: ignore
    todo: ignore
    dead_code: error
  exclude:
    - build/**
    - "**/*.g.dart"
    - lib/flavors.dart
linter:
  rules:
    - public_member_api_docs
    - directives_ordering
    - prefer_relative_imports
